name: 'Kiwi: Force rebase on top of local chromium branch'

on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Setting-up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "Repository manager"

      - name: Fetching Kiwi branch
        run: git fetch origin kiwi

      - name: Switching to Kiwi
        run: git checkout origin/kiwi

      # Note that --ours also corresponds (more intuitively) to the 'Current Changes' in your IDE when resolving conflicts, whereas --theirs corresponds to 'Incoming Changes'
      - name: Rebasing on top of chromium branch
        run: git rebase --strategy-option ours origin/chromium --committer-date-is-author-date

      - name: Preparing new branch
        run: git checkout -b new_kiwi

      # This is done on purpose
      # See: https://redfin.engineering/git-rebasing-public-branches-works-much-better-than-youd-think-ecc9a115aea9
      - name: Pushing Kiwi branch
        run: git push origin new_kiwi:kiwi --force
