name: 'Kiwi: Rebase on top of kiwibrowser:chromium branch'

on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting-up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "Repository manager"

      - name: Adding kiwibrowser repository as upstream
        run: git remote add upstream https://github.com/kiwibrowser/src.next.git

      - name: Fetching kiwibrowser repository
        run: git fetch upstream

      - name: Switching to Chromium
        run: git checkout upstream/chromium

      - name: Loading settings from CHROMIUM_VERSION
        run: |
          if [ -f "CHROMIUM_VERSION" ]; then
            source CHROMIUM_VERSION;
            export $(cut -d= -f1 CHROMIUM_VERSION | grep -vF '#');
            env | grep -F CHROMIUM_ >> $GITHUB_ENV
          fi;

      - name: Creating pull request
        id: pullrequest
        uses: peter-evans/create-pull-request@v3
        with:
          branch: upstream/chromium
          base: kiwi
          delete-branch: false
          signoff: true
          draft: true
          title: "[Rebase] Rebase Kiwi to Chromium version ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }} "
          commit-message: "[Rebase] Rebase Kiwi version ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }}"
          body: |
            Version update initiated by ${{ github.actor }}
            
            This is a rebase. It is *very important* to use "Rebase and merge" to merge this PR.

      - name: Getting pull request URL
        run: |
          echo "Pull request number - ${{ steps.pullrequest.outputs.pull-request-number }}"
          echo "Pull request URL - ${{ steps.pullrequest.outputs.pull-request-url }}"
