name: 'Kiwi: Rebase on top of kiwibrowser:chromium branch'

on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting-up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "Repository manager"

      - name: Adding kiwibrowser repository as upstream
        run: git remote add upstream https://github.com/kiwibrowser/src.next.git

      - name: Fetching kiwibrowser repository
        run: git fetch upstream

      - name: Switching to Chromium
        run: git checkout upstream/chromium

      - name: Loading settings from CHROMIUM_VERSION
        run: |
          if [ -f "CHROMIUM_VERSION" ]; then
            source CHROMIUM_VERSION;
            export $(cut -d= -f1 CHROMIUM_VERSION | grep -vF '#');
            env | grep -F CHROMIUM_ >> $GITHUB_ENV
          fi;

      - name: Creating pull request
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "kiwi"
          PULL_REQUEST_FROM_BRANCH: "chromium"
          PULL_REQUEST_DRAFT: true
          PULL_REQUEST_TITLE: "[Rebase] Rebase Kiwi to Chromium version ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }}"
          PULL_REQUEST_BODY: |
            Version update initiated by ${{ github.actor }}
            
            This is a rebase. It is *very important* to use "Rebase and merge" to merge this PR.
